import 'dart:async';
import 'dart:html';
import 'package:vdom/vdom.dart' as v;
import 'package:liquid/liquid.dart';

class BasicComponent extends VComponent {
  int _elapsed;
  int get elapsed => _elapsed;
  set elapsed(int v) {
    _elapsed = v;
    invalidate();
  }

  String get elapsedSeconds => '${(_elapsed / 1000).toStringAsFixed(1)}';

  BasicComponent(ComponentBase parent, this._elapsed)
      : super(parent, new ParagraphElement());

  List<v.Node> build() {
    return [new v.Text(0, 'Liquid has been successfully '
        'running for $elapsedSeconds seconds.')];
  }

  /// should be auto-generated by Pub Transformer
  void updateProperties(int newElapsed) {
    if (elapsed != newElapsed) {
      elapsed = newElapsed;
    }
  }

  /// should be auto-generated by Pub Transformer
  static VDomComponent virtual(Object key, ComponentBase parent,
                               int elapsed) {
    return new VDomComponent(key, (component) {
      if (component == null) {
        return new BasicComponent(parent, elapsed);
      } else {
        component.updateProperties(elapsed);
        return component;
      }
    });
  }
}

main() {
  final root = new RootComponent();
  final start = new DateTime.now().millisecondsSinceEpoch;
  final basic = new BasicComponent(root, 0);
  root.injectComponent(basic, querySelector('body'));

  new Timer.periodic(new Duration(milliseconds: 50), (t) {
    basic.elapsed = new DateTime.now().millisecondsSinceEpoch - start;
  });
}