part of liquid.components;

/// Just an example
///
/// To properly implement it, we need to add custom events on top of components
class TextInputComponent extends Component {
  String _value;

  TextInputComponent(ComponentBase parent, [this._value = ''])
      : super(parent, new InputElement(type: 'text')) {
    element.onInput.listen((_) {
      _value = (element as InputElement).value;
    });
  }

  void updateProperties(String newValue) {
    if (_value != newValue) {
      _value = newValue;
      invalidate();
    }
  }

  /// should be auto-generated by Pub Transformer
  static VDomComponent virtual(Object key, ComponentBase parent, [String value = '']) {
    return new VDomComponent(key, (component) {
      if (component == null) {
        return new TextInputComponent(parent, value);
      } else {
        component.updateProperties(value);
        return component;
      }
    });
  }

  void render() {
    (element as InputElement).value = _value;
  }

  void update() {
    (element as InputElement).value = _value;
    super.update();
  }
}
