// Copyright (c) 2014, the Liquid project authors. Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

/// Static implementation for VStaticTree, VDynamicTree and VComponent nodes
/// generated by Liquid transformer.
library liquid.static;

import 'dart:html' as html;
import 'package:liquid/vdom.dart' as vdom;

part 'package:liquid/src/static/static_tree.dart';
part 'package:liquid/src/static/dynamic_tree.dart';
