import 'dart:async';
import 'dart:html';
import 'package:vdom/vdom.dart' as v;
import 'package:liquid/liquid.dart';

class Collapsable extends VComponent {
  bool collapsed = false;
  List<v.Node> _collapsableChildren;

  Collapsable(ComponentBase parent, this._collapsableChildren)
      : super(parent, new DivElement());

  List<v.Node> build() => _collapsableChildren;

  void update() {
    if (!isRendered) {
      element.classes.add('collapsable');
      element.onClick.listen((_) {
        toggleCollapse();
      });
    }
    super.update();
  }

  void toggleCollapse() {
    if (collapsed) {
      element.classes.remove('collapsable-close');
      element.classes.add('collapsable-open');
    } else {
      element.classes.remove('collapsable-open');
      element.classes.add('collapsable-close');
    }
  }
}

class BasicComponent extends VComponent {
  int _elapsed;
  int get elapsed => _elapsed;
  set elapsed(int v) {
    _elapsed = v;
    invalidate();
  }

  String get elapsedSeconds => '${(_elapsed / 1000).toStringAsFixed(1)}';

  BasicComponent(ComponentBase parent, this._elapsed)
      : super(parent, new ParagraphElement()) {
    final start = new DateTime.now().millisecondsSinceEpoch;
    new Timer.periodic(new Duration(milliseconds: 50), (t) {
      elapsed = new DateTime.now().millisecondsSinceEpoch - start;
    });
  }

  List<v.Node> build() {
    return [new v.Text(0, 'Liquid has been successfully '
        'running for $elapsedSeconds seconds.')];
  }

  /// should be auto-generated by Pub Transformer
  void updateProperties(int newElapsed) {
    if (elapsed != newElapsed) {
      elapsed = newElapsed;
    }
  }

  /// should be auto-generated by Pub Transformer
  static VDomComponent virtual(Object key, ComponentBase parent,
                               int elapsed) {
    return new VDomComponent(key, (component) {
      if (component == null) {
        return new BasicComponent(parent, elapsed);
      } else {
        component.updateProperties(elapsed);
        return component;
      }
    });
  }
}

main() {
  final root = new RootComponent();
  final collapsable = new Collapsable(root, [BasicComponent.virtual(0, root, 0)]);
  root.injectComponent(collapsable, querySelector('body'));
}