// Copyright (c) 2014, the Liquid project authors. Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

/// Static implementation of virtual dom generated by Liquid transformer.
library liquid.vdom_static;

export 'package:vdom/vdom.dart';
export 'package:liquid/src/vdom.dart';
export 'package:liquid/src/static.dart';