import 'dart:html';
import 'package:vdom/vdom.dart' as v;
import 'package:liquid/liquid.dart';

class HelloComponent extends VComponent {
  String name;

  HelloComponent(ComponentBase parent, [this.name = 'Hello'])
      : super(parent, new DivElement());

  List<v.Node> build() {
    return [new v.Element(0, 'div', [new v.Text(0, 'Hello $name')])];
  }

  /// should be auto-generated by Pub Transformer
  void updateProperties(String newName) {
    if (name != newName) {
      name = newName;
      invalidate();
    }
  }

  /// should be auto-generated by Pub Transformer
  static VDomComponent virtual(Object key, ComponentBase parent,
                               [String name = 'Hello']) {
    return new VDomComponent(key, (component) {
      if (component == null) {
        return new HelloComponent(parent, name);
      } else {
        component.updateProperties(name);
        return component;
      }
    });
  }
}

main() {
  final updateLoop = new UpdateLoop();
  final root = new RootComponent(updateLoop);
  final hello = new HelloComponent(root, 'World');
  root.injectComponent(hello, querySelector('body'));
}